name: nbbestpractices
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.0.1
  - bqplot=0.12.12
  - cufflinks-py=0.17.3
  - jupyter_nbextensions_configurator=0.4.1
  - notebook=6.0.3
  - pandas=0.25.3
  - pandas-profiling=1.4.1
  - plotly=4.5.0
  - python-cufflinks=0.17.3
  - seaborn=0.10.1
  - sqlite=3.30.1
  - pip:
    - ipython-sql==0.4.0
    - sqlalchemy==1.3.17

